
#server.address=127.0.0.1
server.port=8080
spring.application.name=gestao
developer=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
api.security.jwt.secret=AXr7ZMMPP62HKBNm3UDEAVJjOd4A5lr+TzRUX2ikRUHJjrue0K8G2pOcuHLBzwmU8xabpU/Byt7NLkTWT1f0tg==
api.security.jwt.expiration-ms=259200000
security.session.idle-expiration-seconds=43200

logging.level.org.springframework.security=warn
spring.jackson.time-zone=America/Porto_Velho
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.cache.type=redis
logging.level.org.springframework.cache=warn
logging.level.com.gestao=INFO

app.security.cors.allowed-origins=https://genfinance.com.br,https://www.genfinance.com.br
app.security.require-https=false
spring.flyway.enabled=false
xai.api.key=xai-06pEl8MmnGPR2w75lPOJgzDpro6YSiySa8iXuuhefzAyKH06eA6Am2h4pbY3o6z2OnmuCR5Fzg7d1kjL    